### ISSUE TITLE
`bs-platform` dependency is missing from published npm package 

### ISSUE THREAD

**Issue by cgewecke** [JoranHonig/tarantula#1]
Hi 🙂 

Am seeing this error after installing with `yarn add tarantula-fl`;

```
Error: Cannot find module 'bs-platform/lib/js/array.js'
Require stack:
- /Users/cgewecke/code/sc-forks/sushiswap/node_modules/tarantula-fl/src/TestData.bs.js
- /Users/cgewecke/code/sc-forks/sushiswap/node_modules/tarantula-fl/src/index.bs.js
- /Users/cgewecke/code/sc-forks/sushiswap/tarantula.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)
    at Function.Module._load (internal/modules/cjs/loader.js:863:27)
    at Module.require (internal/modules/cjs/loader.js:1043:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/cgewecke/code/sc-forks/sushiswap/node_modules/tarantula-fl/src/TestData.bs.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Module.require (internal/modules/cjs/loader.js:1043:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/cgewecke/code/sc-forks/sushiswap/node_modules/tarantula-fl/src/TestData.bs.js',
    '/Users/cgewecke/code/sc-forks/sushiswap/node_modules/tarantula-fl/src/index.bs.js',
    '/Users/cgewecke/code/sc-forks/sushiswap/tarantula.js'
  ]
}
```

Is resolved if I subsequently run `yarn add bs-platform`

**Comment by JoranHonig** [comment]
I think it should be fixed now!

**Comment by cgewecke** [comment]
Sweet! Thanks.
